[2025-03-13T06:25:06.937+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T06:25:06.980+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_prep_transformation.data_cleaning manual__2025-03-13T05:47:39.846529+00:00 [queued]>
[2025-03-13T06:25:07.009+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_prep_transformation.data_cleaning manual__2025-03-13T05:47:39.846529+00:00 [queued]>
[2025-03-13T06:25:07.010+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-13T06:25:07.059+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): data_cleaning> on 2025-03-13 05:47:39.846529+00:00
[2025-03-13T06:25:07.087+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_prep_transformation', 'data_cleaning', 'manual__2025-03-13T05:47:39.846529+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/data_prep_transformation.py', '--cfg-path', '/tmp/tmpicd41wu_']
[2025-03-13T06:25:07.089+0000] {standard_task_runner.py:105} INFO - Job 232: Subtask data_cleaning
[2025-03-13T06:25:07.094+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-13T06:25:07.095+0000] {standard_task_runner.py:72} INFO - Started process 148 to run task
[2025-03-13T06:25:07.573+0000] {task_command.py:467} INFO - Running <TaskInstance: data_prep_transformation.data_cleaning manual__2025-03-13T05:47:39.846529+00:00 [running]> on host 0aec637a790b
[2025-03-13T06:25:07.976+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_prep_transformation' AIRFLOW_CTX_TASK_ID='data_cleaning' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T05:47:39.846529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T05:47:39.846529+00:00'
[2025-03-13T06:25:08.000+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T06:25:08.101+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-13T06:25:08.153+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T06:25:08.155+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_prep_transformation, task_id=data_cleaning, run_id=manual__2025-03-13T05:47:39.846529+00:00, execution_date=20250313T054739, start_date=20250313T062506, end_date=20250313T062508
[2025-03-13T06:25:08.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T06:25:08.490+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T06:25:08.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
